# This file can be used to override defaults for multirun arguments.
# Arguments of the SimPathsMultiRun object overridden by the command-line

maxNumberOfRuns: 2
executeWithGui: false
randomSeed: 100
startYear: 2019
endYear: 2022
popSize: 20000
integrationTest: true
countryString: United Kingdom
persistCountryYear: false

collector_args:
    persistWealthIncomeStatistics: true
    persistDemographicStatistics: true
    persistAlignmentStatistics: true
    persistPersons: false
    persistBenefitUnits: false
    persistHouseholds: false

parameter_args:
    trainingFlag: true
